trigger: none

parameters:
  - name: Environment
    type: string
    default: 'dev'
    values:
      - dev
      - prod
variables: 
  - ${{ if eq(parameters.Environment, 'dev') }}:
    - group: Terraform-dev
  - ${{ if eq(parameters.Environment, 'prod') }}:
    - group: Terraform-prod

# ----- STAGE 1: Terraform Installer -----
stages:
  - stage: TerraformInstaller1
    displayName: 'Terraform Installer'
    jobs:
      - job: TerraformInstaller
        displayName: 'Terraform Installer'
        steps:
          - task: TerraformInstaller0@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'
          - script: | 
              terraform fmt -check -recursive
              workingDirectory:$(System.DefaultWorkingDirectory)/Terraform
            displayName: 'Check Terraform Format'

  # ----- STAGE 2: Terraform Init and Validate -----    

  - stage: TerraformInitValidate
    displayName: 'Terraform Init and Validate'
    #dependsOn: TerraformFormat
    jobs:
      - job: TerraformInitValidate
        displayName: 'Terraform Init and Validate'
        steps:
          - task: TerraformTaskV4@0
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: $(System.DefaultWorkingDirectory)/Terraform
              #backendServiceArm: ${{ variables.azureServiceConnection }}
              backendAzureRmResourceGroupName: ${{ variables.backendResourceGroup }}
              backendAzureRmStorageAccountName: ${{ variables.backendStorageAccount }}
              backendAzureRmContainerName: ${{ variables.backendContainer }}
              backendAzureRmKey: ${{ variables.backendKey }}
          
          - task: TerraformTaskV4@0
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: $(System.DefaultWorkingDirectory)/Terraform

# ----- STAGE 3: Terraform Plan -----

  - stage: TerraformPlan
    displayName: 'Terraform Plan1'
    #dependsOn: TerraformInitValidate
    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'
        steps:
          # - task: TerraformTaskV4@0
          #   displayName: 'Terraform Init'
          #   inputs:
          #     provider: 'azurerm'
          #     command: 'init'
          #     workingDirectory: $(System.DefaultWorkingDirectory)/Terraform
          #     #backendServiceArm: $(azureServiceConnection)
          #     backendAzureRmResourceGroupName: $(backendResourceGroup)
          #     backendAzureRmStorageAccountName: $(backendStorageAccount)
          #     backendAzureRmContainerName: $(backendContainer)
          #     backendAzureRmKey: $(backendKey)

          - task: TerraformTaskV4@0
            displayName: 'Terraform Plan3'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: $(System.DefaultWorkingDirectory)/Terraform
              #backendServiceArm: $(azureServiceConnection)
              backendAzureRmResourceGroupName: $(backendResourceGroup)
              backendAzureRmStorageAccountName: $(backendStorageAccount)
              backendAzureRmContainerName: $(backendContainer)
              backendAzureRmKey: $(backendKey)
        