trigger: none

parameters:
  - name: Environment
    type: string
    default: 'dev'
    values:
      - dev
      - prod
variables: 
  - ${{ if eq(parameters.Environment, 'dev') }}:
    - group: Terraform-dev
  - ${{ if eq(parameters.Environment, 'prod') }}:
    - group: Terraform-prod

# ----- STAGE 1: Terraform Installer -----
jobs:
- job: TFInstaller_job1
  displayName: 'Terraform Installer'
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
    displayName: Install Terraform latest
    inputs:
      terraformVersion: 'latest'
      workingDirectory: $(System.DefaultWorkingDirectory)/Terraform
      #backendServiceArm: ${{ variables.azureServiceConnection }}
      backendAzureRmResourceGroupName: $(backendResourceGroup)
      backendAzureRmStorageAccountName: $(backendStorageAccount)
      backendAzureRmContainerName: $(backendContainer)
      backendAzureRmKey: $(backendKey)



  # ----- STAGE 2: Terraform Validate -----    

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
    displayName: 'Terraform: Validate'
    inputs:
      provider: azurerm
      command: validate
      workingDirectory: $(System.DefaultWorkingDirectory)/Terraform
      #backendServiceArm: ${{ variables.azureServiceConnection }}
      backendAzureRmResourceGroupName: $(backendResourceGroup)
      backendAzureRmStorageAccountName: $(backendStorageAccount)
      backendAzureRmContainerName: $(backendContainer)
      backendAzureRmKey: $(backendKey)

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
    displayName: 'Terraform: Plan'
    inputs:
      provider: azurerm
      command: plan
      workingDirectory: $(System.DefaultWorkingDirectory)/Terraform
      #backendServiceArm: ${{ variables.azureServiceConnection }}
      backendAzureRmResourceGroupName: $(backendResourceGroup)
      backendAzureRmStorageAccountName: $(backendStorageAccount)
      backendAzureRmContainerName: $(backendContainer)
      backendAzureRmKey: $(backendKey)
 